### PR TITLE
Use monochrome symbol for directory tree

### PR DESCRIPTION
**Pull request by jonesbusy**
**Before**

before

**After**

(default)
default

(dark)
dark

### Testing done

Only checking visual

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by basil** [comment]
I don't mind approving this if necessary, but I must admit that the new image looks worse than the original one to me. The original one is very clearly a folder with subfolders. I'm not sure what the second image represents. It looks more like the pins of a microprocessor to me and it is not obviously a folder/subfolders at all.

**Comment by jonesbusy** [comment]
I will try to do an other proposal

**Comment by jonesbusy** [comment]
Does it look more like subdirectories now ?

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
