### PR TITLE
[JENKINS-44256] Support for sandbox mode, system groovy scripts.

### PR DESCRIPTION
**Pull request by per-bohlin**
https://issues.jenkins-ci.org/browse/JENKINS-44256

### CODE REVIEW

**Comment by per-bohlin** [comment]
Might have found a problem in the implementation. Please hold off until I confirm it is working.

**Comment by per-bohlin** [comment]
Rebased on top of currently HEAD of master
Fixed example to match required format.
I've not had time figure out why writing an XML format that results in the deprecated constructor call in script-security results in a transformation from plain path to URI for the classpaths, while using the current databound constructor XML format, require the classpath entry to be in URI format.

**Comment by per-bohlin** [comment]
@daspilker, any change you can have a look at this implementation and asses when it can be merged in; or if it needed, propose improvements?
We are currently using our own version due to this missing feature but it would be great if can go back to using the official version. Thanks!

**Comment by jk563** [comment]
Am I correct in saying this enables us to use `sandbox()` as a step in our job definition?

**Comment by per-bohlin** [comment]
@jk563, sorry for my late reply
This feature allows you to configure a system groovy script build step to be run in sandbox mode.
The system groovy script build-step has offer a check-box, marking it to run in sandbox mode, which affects script execution security. This has not been able to set, defaulting to non-sandbox mode.
We needed to run system groovy scripts in sandbox mode, hence this feature.

**Comment by chancez** [comment]
Does this change anything about being able to use the overloaded `/` and `<<` operators within job DSL configure blocks  when using the sandbox?

**Comment by per-bohlin** [comment]
@chancez, My implementation is very much based on the existing implementation and I've made no effort to remedy any such shortcomings if they existed in the original. Sorry.
Now that you made me aware of it, I'll see if I can figure out how to fix that as well, but I can't make any promises of when.
Thank you for the feedback.

**Comment by daspilker** [comment]
@per-bohlin sorry for answering late.

I'm replacing this PR by #1075. I wanted to integrate sandbox support in to existing calls for `systemGroovyCommand` instead of adding a new variant.

**Pull request closed without merging**
