### PR TITLE
Add Phabricator lint configuration options

### PR DESCRIPTION
**Pull request by sectioneight**
I just added this to the phabricator differential plugin in release 1.9.7.

I've verified that the tests still pass, but I'm not sure if there's more work to be done, as I've never touched this plugin before.

This was added in https://github.com/uber/phabricator-jenkins-plugin/commit/f4e6901e64da767ef0148f59b96f6e15bf0a3271

### CODE REVIEW

**Comment by sectioneight** [comment]
cc @jjx can you sanity check this for me?

**Comment by sectioneight** [comment]
cc @ignas

also bump at maintainers?

**Comment by jjx** [comment]
lgtm!

**Comment by sectioneight** [comment]
@daspilker ping?

**Comment by daspilker** [comment]
Add some tests for the new options.

The Phabricator plugin does not store the "Maximum bytes of lint to read" setting, it always defaults to 100000. This should be fixed in the Phabricator plugin before we add Job DSL support.

**Comment by Blackbaud-OdsDeploy** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
