### PR TITLE
Restore Multijob phase support in conditionalSteps

### PR DESCRIPTION
**Pull request by wolfs**
Make it possible to execute a Multijob phase conditionally.

It would probably be better to wrap the steps in the conditionalSteps within a Closure and adjust the dsl like this:
```groovy
conditionalSteps {
   steps {
      shell('echo Hello World')
   }
}
```

### CODE REVIEW

**Comment by daspilker** [comment]
Why is it broken? What is the problem? I don't like the methodMissing/propertyMissing solution because it breaks IDE support. How about wrapping the steps into a closure as you suggested and using methodMissing/propertyMissing as a deprecated fallback for compatibility.

**Comment by wolfs** [comment]
Currently, a phase cannot be configured by the job-dsl to be part of conditionalStep, e.g. the following does not work:
```groovy
condition {
                alwaysRun()
            }
            runner('Fail')
            phase {
                phaseName 'Second'
                job('JobA')
            }
```
See the corresponding test in MultiJobStepContextSpec.

The reason for this is that the ConditionalStepsContext is a subclass of StepContext and not of MultiJobStepContext.
One possible solution to this is the workaround I committed.
I think inheritance is the wrong abstraction here. A ConditionalStep is not a Step but contains Steps.
Do you have any idea how to make this work with IDE support?

**Comment by daspilker** [comment]
Ah, I see.

ConditionalStepsContext should not be a subclass of StepContext. It should have a nested steps context for the steps. Maybe generics can help?

```groovy
class ConditionalStepsContext<T extends StepContext> {
    ...
    void steps(@DslContext(T) Closure stepContext) {
        ...
    }
}
```

IDEA does not complain about the type parameter for the annotation, so it might work. Can you try that?

**Comment by wolfs** [comment]
I tried this out in pull #516. IDE-Support does not seem to work for me - I cannot imagine how the type parameter could be determined. If you want to have a shot at it feel free to go - I really need this feature and can do without IDE-Support in this limited case.

**Comment by daspilker** [comment]
See #517.

**Pull request closed without merging**
