### PR TITLE
add discard old builds option

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by daspilker** [comment]
What is the benefit of adding this? Jenkins will automatically migrate the old [logRotator](https://jenkinsci.github.io/job-dsl-plugin/#path/job-logRotator) to the new `BuildDiscarderProperty`. I see no advantage in having two DSL methods to do the same thing.

**Comment by kamilszymanski** [comment]
When migrating manually created jobs to DSL scripts I often start with a test that compares existing config.xml with a generated one and unless you are aware of such automatic translation for `logRotator` you end up searching for a "missing" way to generate `BuildDiscarderProperty` or using configure block.
Having 2 DSL methods is as confusing as not having the one that generates expected xml and I'd prefer to have both of them rather than assume all interested job-dsl users know about this automated translation.

**Comment by daspilker** [comment]
Ah, interesting. It's always nice to hear how people use Job DSL.

Have you tried the new [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL)? It already supports this and any strategy that is provided by other plugins.

```
job('example') {
  properties {
    buildDiscarderProperty {
      strategy {
        logRotator {
          daysToKeepStr('1')
          numToKeepStr('2')
          artifactDaysToKeepStr('3')
          artifactNumToKeepStr('4')
        }
      }
    }
  }
}
```

**Comment by daspilker** [comment]
I opened a pull request for Jenkins core so that we can use `buildDiscarder` instead of `buildDiscarderProperty`: https://github.com/jenkinsci/jenkins/pull/2358

**Pull request closed without merging**
