### PR TITLE
[JENKINS-33359] Add maven incrementalBuild option

### PR DESCRIPTION
**Pull request by khmarbaise**
o Added incrementalBuild into MavenJob.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Should this kind of options better implemented having a method with default parameter like:

````
    void incrementalBuild(boolean incrementalBuild = false) {
   ...
``` 
or without as i did?

**Comment by daspilker** [comment]
I changed the signature to `void incrementalBuild(boolean incrementalBuild = true)`.

With a default parameter set to `false`, the DSL would be counterintuitive. The following snippet would disable incremental builds, but the script reads as if the feature is enable.

```groovy
mavenJob('example') {
    incrementalBuild()
}
```

**Comment by khmarbaise** [comment]
Hm..but in the majority of the cases the incrementalBuild is turned off (also in Jenkins it's the default to turned off) only if explicitly activated (true). Would it be a better idea to name the method different ?

**Comment by daspilker** [comment]
All boolean options in Job DSL work like this. If you use `foo()`, the feature is enable. If you do not call `foo`, you get the default value as set by the plugin to be configured. Or you can explicitly specify a value using `foo(boolean)`.

**Pull request merged**
