### PR TITLE
feat: expose http timeout options

### PR DESCRIPTION
**Pull request by jakub-bochenski**
recently added in https://github.com/jenkinsci/parameterized-remote-trigger-plugin/pull/66/files

alternatively exposing the autogenerated DSL would solve this too, I'm not sure how to do it though

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
The build failed on groovy download. How do you retry builds here? I've seen some people close and reopen the PR.

```
[2020-04-15T12:36:18.167Z] + ./gradlew --no-daemon cleanTest build

[2020-04-15T12:36:18.551Z] Downloading https://services.gradle.org/distributions/gradle-5.6.4-all.zip

[2020-04-15T12:36:20.869Z] ........................................................................................................Sending interrupt signal to process

[2020-04-15T12:36:20.993Z] .............................

[2020-04-15T12:36:21.090Z] script returned exit code 143
```

**Comment by jakub-bochenski** [comment]
Test this please? :P

**Comment by daspilker** [comment]
These options are already supported by [Dynamic DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL). I am no longer merging pull requests for features that are supported by Dynamic DSL.

````
job('example') {
    steps {
        remoteBuildConfiguration {
            blockBuildUntilComplete(true)
            httpGetReadTimeout(1000)
            httpPostReadTimeout(2000)
            job('test-job')
            parameters('foo=bar')
            remoteJenkinsName('test')
        }
    }
}
````

**Comment by jakub-bochenski** [comment]
OK thanks, I was under impression that this is not covered by dynamic DSL

**Comment by daspilker** [comment]
What led to that impression? Is there something that can be improved wrt Dynamic DSL?

**Comment by jakub-bochenski** [comment]
I guess I just checked the `remoteTrigger` docs. 
Would be nice if the API reference had a note/link pointing to the dynamic version.

**Comment by jakub-bochenski** [comment]
^ that was a comment about general case of having both static and dynamic DSL

for this particular plugin -- shouldn't the static version be deprecated then?

**Comment by daspilker** [comment]
Thanks for the feedback, having a link to the dynamic version would be nice indeed.

I keep the static version as long as it has not become incompatible with newer plugin versions. So users who do not need new features are not forced to update.

**Comment by jakub-bochenski** [comment]
> I keep the static version as long as it has not become incompatible with newer plugin versions. So users who do not need new features are not forced to update.

I mean just mark them as deprecated to notify users that there are other steps available (the dynamic ones)

**Pull request closed without merging**
