### PR TITLE
[JENKINS-26086] ViolationsContext can't set min=0

### PR DESCRIPTION
**Pull request by LawYard**

### CODE REVIEW

**Comment by daspilker** [comment]
Please fix this for `max` and `unstable` as well. And add a test case to `PublisherContextSpec`.

**Comment by LawYard** [comment]
Done!

**Comment by daspilker** [comment]
Change to test case to also test for `max` and `unstable` being zero.

**Comment by LawYard** [comment]
Hi! [According to violations plugin](https://github.com/jenkinsci/violations-plugin/blob/cab7103bd00057c8b97f7b5a2cd4cbb461af6603/src/main/java/hudson/plugins/violations/TypeConfig.java#L177) `max` cant be equal to `0`:

```java
    /**
     * Ensure that max is &gt; min and that
     * both are positive.
     */
    public void fix() {
        if (min < 0) {
            min = 0;
        }
        if (max <= min) {
            max = min + 1;
        }
    }
```

Also `unstable` cant be equal or less than `0`:
```java
/** Default unstable */
    public static final int DEFAULT_UNSTABLE = 999;
    /** UNSTABLE BLANK */
    public static final int UNSTABLE_BLANK = -4646;

  /**
     * Get the unstable value
     * @return the unstable value
     */
    public Integer getUnstable() {
        if (unstable == null) { // OLD CONFIG
            unstable = DEFAULT_UNSTABLE;
        }
        if (unstable == UNSTABLE_BLANK) {
            return null;
        }
        return unstable;
    }

    /**
     * Set the unstable value.
     * @param unstable the value to use.
     */
    public void setUnstable(Integer unstable) {
        if (unstable <= 0) {
            unstable = UNSTABLE_BLANK;
        }
        this.unstable = unstable;
    }
```

Should we fix that or thats another story and should be fixed within other PR?

**Comment by daspilker** [comment]
Good point, but let's fix that in another PR. Just amend the tests.

**Comment by LawYard** [comment]
Ready! Check please

**Pull request merged**
