### PR TITLE
JENKINS-26333 - Support for Custom Job Icon Plugin

### PR DESCRIPTION
**Pull request by kmoens**
support for custom icon plugin

### CODE REVIEW

**Comment by daspilker** [comment]
I don't think that this plugin is a good candidate for DSL support. Unlike your example, the user has to look at the XML to determine the internal ID of the icon:

```groovy
job {
//    customIcon('myFancyIcon.png')
    customIcon('6e63ee51fc9a8526befe96fa5d7c5498d80f515f.png')
}
```

If there is no way to configure the icon without having to look at the XML, I'm going to close this pull request.

**Comment by kmoens** [comment]
Judging from how the plugin works, I fear there is no other way... Except maybe if we push the images itself too with the DSL.

**Comment by daspilker** [comment]
I'm going to add support for uploading user content, see #475. After that has been merged I will have a second look at this PR.

**Comment by daspilker** [comment]
Now it's possible to upload an icon from the DSL:

```groovy
userContent('customIcon/job.png', streamFileFromWorkspace('icons/job.png'))

job('example') {
    properties {
        customIcon('job.png')
    }
}
```

I rebased your changes and merged them manually.

**Pull request closed without merging**
