### PR TITLE
Fix broken links, images, Markdown in docs.

### PR DESCRIPTION
**Pull request by declension**

### CODE REVIEW

**Comment by daspilker** [comment]
Most of your changes break the links in the wiki. The wiki should be the primary source of information for the latest release. Please make sure that all links work on the wiki.

**Comment by declension** [comment]
Oh, right, sorry. Didn't realise that these were handled separately - I'll have a look. How can I test them locally / on a fork?

**Comment by daspilker** [comment]
You can push the docs to the wiki of your fork. Just change the repo URL for the GitHub Pages plugin (https://github.com/jenkinsci/job-dsl-plugin/blob/master/build.gradle#L173) and run `./gradlew publishGhPages`.

**Comment by declension** [comment]
Thanks, I see what you mean now... frustrating trying to support two setups. I'll close this PR and maybe just pull out of the small tweaks that don't affect linkage.

**Comment by daspilker** [comment]
OK, thanks. IMHO GitHub should fix that.

**Pull request closed without merging**
