### PR TITLE
Make permissions matrix-auth-3.0+ compatible

### PR DESCRIPTION
**Pull request by eva-mueller-coremedia**
Make permissions matrix-auth-3.0+ compatible by adding support to explicitly assign permissions to groups or users.

With https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.0 ambiguous permissions will show a warning. With this change, matrix-auth-3.0+ users can resolve the warning by using the appropriate methods.

Closes #1249

See also https://issues.jenkins.io/browse/JENKINS-67411

### Testing done

Added test cases and manually deployed and tested the hpi on a Jenkins 2.440.3 instance.

#### Job DLS
config-job-dsl

#### UI
config-ui

#### XML
config-xml

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by eva-mueller-coremedia** [comment]
@basil @jamietanna - are you still the main maintainers? It would be great if you could have a look at this PR.

**Comment by jamietanna** [comment]
As per https://github.com/jenkinsci/job-dsl-plugin?tab=readme-ov-file#jenkins-job-dsl-plugin I'm looking for support with maintainence.

I appreciate that this is fixing a warning, but I think my priority - if I were to be able to have time to support the plugin - would be to triaging the other outstanding issues and work out priority from there

**Comment by eva-mueller-coremedia** [comment]
> As per [jenkinsci/job-dsl-plugin#jenkins-job-dsl-plugin](https://github.com/jenkinsci/job-dsl-plugin?tab=readme-ov-file#jenkins-job-dsl-plugin) I'm looking for support with maintainence.
> 
> I appreciate that this is fixing a warning, but I think my priority - if I were to be able to have time to support the plugin - would be to triaging the other outstanding issues and work out priority from there

Sure, prioritize as best for you. Glad to see that there is a maintainer left.

I would like to emphasize that this also addresses thttps://issues.jenkins.io/browse/JENKINS-67411 - maybe a coin to raise this issue in its priotity.

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
