### PR TITLE
[Jenkins 21880] weblogic-deployer-plugin support

### PR DESCRIPTION
**Pull request by matthiasbalke**
This pull request adds support for the weblogic-deployer-plugin.

As this is my first Groovy project I would like to get some feedback on code quality and architecture. So please review my code. Especially I'm unsure whether the **task** sub section is implemented right. In the mean time, I'll add a last peace of code for the deployment trigger parameters.

I tested the plugin on Jenkins 1.532.1 and weblogic-deployer-plugin 2.9.1 running on Windows 2008 R2 SP1 deploying to WebLogic 12c. Also tested on Jenkins 1.480 weblogic-deployer-plugin 2.9.1 on Windows 7.

### CODE REVIEW

**Comment by daspilker** [comment]
Are you interested in picking this up or shall I close the pull request?

**Comment by matthiasbalke** [comment]
Hey @daspilker yes I'm really interested. As I'm upgrading our jenkins server the next weeks, I really need to get this working. But I haven't had the time until now.

**Comment by daspilker** [comment]
OK great. A lot has changed in between. Please rebase your changes to master and have a look at [CONTRIBUTING.md](https://github.com/jenkinsci/job-dsl-plugin/blob/master/CONTRIBUTING.md).

**Comment by matthiasbalke** [comment]
It seems impossible for me to get this rebased. I'll start a new branch and add the weblogic deployer plugin support from scratch. Afterwards I'll open a new pull request.

Does that makes sense for you?

**Comment by daspilker** [comment]
Sounds OK, do whatever works for you.

**Pull request closed without merging**
