### PR TITLE
[JENKINS-29504] added support for Xcode plugin

### PR DESCRIPTION
**Pull request by marc-guenther**
Added support for the
- `xcode` and
- `import developer profile`

build steps of Xcode plugin

### CODE REVIEW

**Comment by daspilker** [comment]
How does this compare to #358?

**Comment by daspilker** [comment]
I have been rejecting pull requests which add DSL methods for setting plain text passwords. In this case the keychain password is unencrypted. I started a discussion on the mailing list about this, see https://groups.google.com/d/msg/job-dsl-plugin/59xhodIgrsY/L2_GrZNEBQAJ.

I'm also not very delighted about reviewing 30 options. Do you really need all those options? If not, please remove all options that you don't need.

**Comment by marc-guenther** [comment]
Do be honest, I don't like this entire pull request at all:
- too much copy/paste. These plethora of options new exist 3 times in actual source code, several times in test source code, and once in documentation. I would like to get rid of at least the 3 times in the real source code.
- All the options are simply a copied from the config.xml as a flat list. They could probably be organized into more convenient methods, which group several dependant options into one method call. Also these booleans like are `buildIpa` are completely unneccesary, as setting eg. `ipaName` could simply implicitely set the boolean to true in the xml. No need to do that manually.
- Best thing would be it the XCode plugin itself could contribute the DSL commands. I remember hearing about this somewhere, but now cannot find it anywhere...

Need to think some about this...

**Comment by daspilker** [comment]
The documentation for contributing DSL from other plugins is in the [wiki](https://github.com/jenkinsci/job-dsl-plugin/wiki/Extending-the-DSL).

EIther move the DSL to the XCode plugin or just keep the options you need to set for your config. Other options can be added later on in a separate pull request.

**Comment by daspilker** [comment]
Do you want to pick this up? Otherwise I will close the PR.

**Comment by marc-guenther** [comment]
Unfortunately, not in the near future. We currently use it internally like it is here, but that's not really fit for general usage. I would rather go with the approach like in #358, but I don't see I will have time for that anytime soon.

**Comment by daspilker** [comment]
OK, please reopen the PR or open a new one if you find some time to work on this.

**Pull request closed without merging**
