### PR TITLE
[JENKINS-29849] Add github-plugin projectUrl

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by daspilker** [comment]
As I mentioned in the JIRA ticket, the GitHub project URL will be set when using the `github` method of the `RemoteContext`, see https://github.com/jenkinsci/job-dsl-plugin/blob/job-dsl-1.36/job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/scm/RemoteContext.groovy#L35-L58. It's even mentioned in the docs, see https://github.com/jenkinsci/job-dsl-plugin/wiki/Job-reference#git. So having an explicit method should not be necessary.

**Comment by KostyaSha** [comment]
@daspilker github PP is all-sufficient feature. It doesn't require configuring SCM. Git scm "auto" browser correctly detects what browser to use, so no need configuring it explicitly. 
I will be also glad to manage github job dsl integration in github plugin as you can mislead it's users.

**Comment by KostyaSha** [comment]
PS project property probably will be extended in future, so calling it with 'url' is not right. GH PP should be single property 
```
github(url)
```
or later possibly 
```
github {
  properties...
}
```

cc @lanwen

**Comment by daspilker** [comment]
OK, @KostyaSha convinced me that it's a good idea to have this as a separate method. But new `JobProperties` should go to the `PropertiesContext`. @aduprat, can you move the `githubProjectUrl` method to `PropertiesContext`?

**Comment by aduprat** [comment]
I will do

**Comment by lanwen** [comment]
@daspilker Is any way to prefer dsl from extension (from target plugin) to dsl from this plugin (if method requires plugin).

To migrate all dsl management from this plugin to targeted plugin?

**Comment by daspilker** [comment]
@lanwen no, the core DSL will always win.

**Comment by aduprat** [comment]
@daspilker I've rebased & move the method

**Comment by KostyaSha** [comment]
@daspilker win in what? We can't guarantee compatibility when code related to plugin is not in plugin.
I think they issue is in documentation generation?

**Comment by lanwen** [comment]
@KostyaSha win if there 2 methods with same signature - from extension point and from this plugin

**Pull request merged**
