### PR TITLE
removed anything that has been deprecated in 1.47

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by sheehan** [comment]
Still waiting for someone to merge my PR for the Slack plugin https://github.com/jenkinsci/slack-plugin/pull/236. I was hoping someone would get to it before we removed it.

**Comment by daspilker** [comment]
@sheehan 😞 That's still open?!?  Can you fix the merge conflict in https://github.com/jenkinsci/slack-plugin/pull/236?

**Comment by sheehan** [comment]
@daspilker fixed!

**Comment by daspilker** [comment]
I merged everything except for the Slack publisher. But I do not want this PR to be open forever, so we must really try to get https://github.com/jenkinsci/slack-plugin/pull/236 merged.

**Pull request merged**
