### PR TITLE
[JENKINS-22151] Enhanced Extension point

### PR DESCRIPTION
**Pull request by daspilker**
This resolves [JENKINS-22151](https://issues.jenkins-ci.org/browse/JENKINS-22151) and should allow to implement [JENKINS-21750](https://issues.jenkins-ci.org/browse/JENKINS-21750) with the extension point.

### CODE REVIEW

**Comment by denschu** [comment]
Hi @daspilker,

thanks for implementing the Extension point stuff :-)

I'm actually trying to implement the Promotion Plugin Extension and I have a problem with the ContextExtensionPoint.

Given is the following code snippet (PromotionsExtensionPoint.java):

	@DslExtensionMethod(context = PropertiesContext.class)
	public Object promotions(Runnable runnable, DslEnvironment dslEnvironment) {
		PromotionsContext promotionsContext = new PromotionsContext();
		executeInContext(runnable, promotionsContext);
		return null;
	}

and the corresponding PromotionsContext.groovy:

```
class PromotionsContext implements Context  {
    def promotion(Closure closure = null) {
		System.out.println("promotion: " + closure);
    }
}
```

When I run this example dsl:
```
job {
	name('promotion-job')
	properties {
		promotions {
			promotion {
			    name('dev')
			}
		}
	}
}
```
... I always get this exception:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: javaposse.jobdsl.dsl.helpers.properties.PropertiesContext.promotion() is applicable for argument types: (script14380043214471369759433$_run_closure1_closure2_closure3_closure4) values: [script14380043214471369759433$_run_closure1_closure2_closure3_closure4@c6d095]
```

For me it's really weird that it searches for the method "promotion" in the PropertiesContext class. Do you have an idea whats going wrong at this point?

Thank you and Regards...
Dennis

**Comment by daspilker** [comment]
Hm, not sure. Have you pushed your code into a public repo so that I can have a look?

**Comment by denschu** [comment]
Thanks for your fast reply :-) 

I've created a fork from my colleague Thomas into our company repo and updated some versions etc. You can find it here: https://github.com/codecentric/job-dsl-promotions-plugin
The original issue was that we got a ClassCastException in line 27 of this class: https://github.com/codecentric/job-dsl-promotions-plugin/blob/master/src/main/java/org/jenkinsci/plugins/jobdsl/promotions/PromotionsExtensionPoint.java

Maybe it has something to do with using Groovy to extend the DSL (PromotionsContext.groovy)...

**Comment by denschu** [comment]
Mh, this seems to work:

```
job {
	name('promotion-job')
	properties {
		promotions {
			promotion('dev') 
		}
	}
}
```
PromotionsContext.groovy:
```
    def promotion(String name) {
		System.out.println("promotion: " + name);
    }
```

**Comment by daspilker** [comment]
If you get a ClassCastException when trying to cast to Closure, the reason might be that the Jenkins core brings a Groovy runtime and the Job DSL plugin brings it's own Groovy runtime. The plugin uses some Jenkins class loader magic to separate the two which may cause the problems. I'm going to remove the extra runtime in the next Job DSL release. So you can either wait a few days or try to implement the extension point in pure Java. Or you try a custom Job DSL build with this branch: https://github.com/CoreMedia/job-dsl-plugin/tree/remove-grab.

**Comment by denschu** [comment]
Ok, I will give it a try with the custom build :-) Thank you for your help!

**Comment by denschu** [comment]
That seems to work :+1: 

But I don't see any detailed log output in the console from the Generator Job. I see only this:

```
Gestartet durch Benutzer anonymous
Baue in Arbeitsbereich /Users/denschu/git/job-dsl-promotions-plugin/work/jobs/generator/workspace
Processing provided DSL script
Warning: (DSL script, line 1) job is deprecated
Warning: (DSL script, line 2) name is deprecated
ERROR: (DSL script, line 4) Error calling extension
Finished: FAILURE
```

Any hints on how to switch detailed logging on? :-)

**Comment by daspilker** [comment]
The stack trace should be logged to the Jenkins log, e.g. Manage Jenkins -> System Log -> All Jenkins Logs or /var/log/jenkins/jenkins.log.

**Comment by denschu** [comment]
Mh, I see only the normal system output from Jenkins in the log, but not from the executed generator job. With version 1.35 it worked fine. I started it with "mvn hpi:run"...

**Comment by daspilker** [comment]
Ah, I changed the logging in 1.36-SNAPSHOT. You need to add a new log recorder for `javaposse.jobdsl.plugin` in Manage Jenkins -> System Log and set the level to `FINE`.

**Comment by denschu** [comment]
Ok, great, the logging works now :-)

Now I get a ClassNotFoundException:

```
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
	at org.jenkinsci.plugins.jobdsl.promotions.PromotionContext.name(PromotionContext.groovy:27)
...
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 214 more
```

I will dive into it tomorrow... Thank you so much for your help!

**Comment by denschu** [comment]
Hi @daspilker,

the plugin seems to work now... but I ran into the next problems ;-)

The JenkinsJobManagement.callExtension-method creates the XML with a special XStream-Implementation. 

line 409 of JenkinsJobManagement

```
Object result = Iterables.getOnlyElement(candidates).call(getSession(item), args);
return new XmlParser().parseText(Items.XSTREAM2.toXML(result));
```

Whats the simplest way to write the correct plugin-name into the root node attribute like in this example:

```
<hudson.plugins.promoted__builds.JobPropertyImpl plugin='promoted-builds@2.15'>
			<activeProcessNames>
				<string>dev</string>
				<string>dev2</string>
			</activeProcessNames>
</hudson.plugins.promoted__builds.JobPropertyImpl>
```

Is it maybe a better idea to be able to return the already generated XML from the Extension?

Thanks
Dennis

**Comment by denschu** [comment]
The actual implementation ist available here:
https://github.com/codecentric/job-dsl-promotions-plugin

And here the JobProperty as Java POJO:
https://github.com/codecentric/job-dsl-promotions-plugin/blob/master/src/main/java/org/jenkinsci/plugins/jobdsl/promotions/JobProperty.java

**Comment by daspilker** [comment]
@denschu that's the correnc XStream instance for creating job XML configs, see https://github.com/jenkinsci/jenkins/blob/jenkins-1.565/core/src/main/java/hudson/model/Items.java#L400.

The idea is that a plugin can directly use it's POJOs as return values, because that's avoids the XML generation, the POJOs exist anyway and it will always generate the correct XML.

I recommend to try to use the JobPropertyImpl from the Promoted Builds plugin. Ideally the Job DSL extension for the Promoted Builds plugin should be a part of the Promoted Builds plugin to avoid problems across different versions of the Promoted Build plugin and changes or refactorings will also be applied to the DSL extension with the need to release an additional plugin.

**Comment by denschu** [comment]
Ah ok, thanks, I will try this solution :-)

**Comment by denschu** [comment]
Mh, the JobPropertyImpl from the Promoted Build plugin needs access to the actual project:

**Comment by denschu** [comment]
Ok, one solution would be, if we completely integrate the DSLExtension into the promoted-builds-Plugin, but in the first step it would be very nice to separate the DSL extension development from the main plugin.

I think generally it's a problem to integrate DSL extensions into the plugin. It would also slow down the whole process.

**Comment by daspilker** [comment]
Ah, I see.

You do not need the plugin attribute on the root node anyway. The Job DSL does not generate these attributes and everything works fine. So you can still use your custom POJO.

**Comment by denschu** [comment]
Is there already a planned release date for 1.36? :-)

Thank you for your help!

**Comment by denschu** [comment]
Mh, I tested the POJO-stuff from above in more detail and I have some bad news... The attribute "plugin='job-dsl-promotions@1.0-SNAPSHOT'" is generated by the special XStream-marshaller which is used by the Job DSL. The generator runs successful, but the Promotions doesn't show up in the job configuration.

This does NOT work:
```
<hudson.plugins.promoted__builds.JobPropertyImpl plugin='job-dsl-promotions@1.0-SNAPSHOT'>
            <activeProcessNames>
                <string>prod</string>
            </activeProcessNames>
 </hudson.plugins.promoted__builds.JobPropertyImpl>
```

But this works (I changed it manually in the file system):
```
<hudson.plugins.promoted__builds.JobPropertyImpl plugin=promoted-builds@2.15'>
            <activeProcessNames>
                <string>prod</string>
            </activeProcessNames>
 </hudson.plugins.promoted__builds.JobPropertyImpl>
```

So it seems to be, that there are some side effects with the plugin attribute.

Furthermore I found out that the POJO needs to extend the JobProperty-class. Otherwise I get a ClassCastException during job generation:

```
FATAL: org.jenkinsci.plugins.jobdsl.promotions.JobProperty cannot be cast to hudson.model.JobProperty
java.lang.ClassCastException: org.jenkinsci.plugins.jobdsl.promotions.JobProperty cannot be cast to hudson.model.JobProperty
	at hudson.model.Job.onLoad(Job.java:212)
	at hudson.model.AbstractProject.onLoad(AbstractProject.java:318)
```

That would be the solution, but it looks not very "clean":
```
@XStreamAlias("hudson.plugins.promoted_builds.JobPropertyImpl")
public class PromotionJobProperty extends hudson.model.JobProperty<Job<?,?>> {
	
	List<String> activeProcessNames = new ArrayList<String>();

	public PromotionJobProperty(List<String> activeProcessNames) {
		this.activeProcessNames = activeProcessNames;
	}	
}
```

**Comment by denschu** [comment]
I deleted my last comment, because there is some weird behaviour in my local testing environment. I've to research some more details :-)

**Comment by denschu** [comment]
Maybe this discussion is interesting for you, @daspilker:
https://groups.google.com/d/msgid/jenkinsci-dev/16a2df29-c855-45bb-b9e7-de7b092bc3d7%40googlegroups.com?utm_medium=email&utm_source=footer

**Pull request merged**
