### PR TITLE
Support building on Java 17 and 21

### PR DESCRIPTION
**Pull request by basil**
Without dropping support for Java 11, add support for running `mvn clean verify` on Java 17 and 21.

### CODE REVIEW

**Review by jamietanna — APPROVED** [review]

**Comment by basil** [comment]
@jamietanna Thanks for the review. Could this PR please be merged and released to unblock plugin compatibility testing (PCT) on Java 17/21?

**Comment by jamietanna** [comment]
Sure, I should have some time in the next couple of days to push a release!

**Comment by jamietanna** [comment]
@basil I've just given the release steps a go and hit:

```
$ mvn release:prepare release:perform
...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:job-dsl:${revision}${changelist}, /home/jamie/workspaces/job-dsl-plugin/job-dsl-plugin/pom.xml, line 10, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:job-dsl:1.85-SNAPSHOT (/home/jamie/workspaces/job-dsl-plugin/job-dsl-plugin/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ org.jenkins-ci.plugins:job-dsl:${revision}${changelist}, /home/jamie/workspaces/job-dsl-plugin/job-dsl-plugin/pom.xml, line 10, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
mvn release:prepare release:perform  23.38s user 1.51s system 52% cpu 47.453 total
```

Is this one you've seen before?

**Comment by basil** [comment]
Have you tried building in the parent directory?

**Comment by jamietanna** [comment]
This was from the root module - it appears to have been me running JDK8, JDK11 is now working.:clapping:

**Pull request merged**
