### PR TITLE
Adds support for XCode Plugin

### PR DESCRIPTION
**Pull request by rymndhng**
Adds support for [XCode Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Xcode+Plugin)

This adds two new steps and a new wrapper.

- **Steps**: xcodeDeveloperProfile, xcode
- **Wrappers**: osxKeychain

### CODE REVIEW

**Comment by lacostej** [comment]
Does this mean that if we make changes to the xcode plugin, we should consider updating the context in the job dsl plugin ?

**Comment by rymndhng** [comment]
@lacostej yeah, we should keep them in sync!

**Comment by daspilker** [comment]
Apart from missing documentation and other issues my biggest concern is that the keychain password is stored in plain text and that encourages DSL users to store the password in plain text in their DSL scripts and probably in SCM. That's a no-go. Either remove the keychain settings if that's optional or the XCode plugin must use the Credentials plugin to store the password in safe manner.

**Comment by rymndhng** [comment]
Both suggestions sound reasonable. I'll update the patch later today.

**Comment by daspilker** [comment]
So now this can only be used with unprotected keychains? A user can not simply choose to use the Credentials plugin for that, it has to be fixed in the XCode plugin.

**Comment by daspilker** [comment]
I started a discussion on the mailing list about handling credentials in the DSL: https://groups.google.com/forum/#!msg/job-dsl-plugin/59xhodIgrsY/L2_GrZNEBQAJ

**Comment by marc-guenther** [comment]
@rymndhng interested in working together on this one? I have a similar pull request open (not knowing about yours), and there were some things I liked better in yours, but now I see you have completely removed all commits.... ?!? What are your plans for this?

**Comment by rymndhng** [comment]
Ah yeah, I killed that while doing some cleaning, it was on my `master` branch :P previously.

Feel free to take a stab at getting getting it up to speed -- I haven't touched the branch for 7 months. It's available here https://github.com/rymndhng/job-dsl-plugin/tree/add-xcode-plugin

**Pull request closed without merging**
