### PR TITLE
Fix: Don't destroy credentials when re-creating organization folder

### PR DESCRIPTION
**Pull request by jfroche**
Extend the current code which does it for cloudbee Folder to Organization Folder.

refs JENKINS-44681
Previous fix for cloudbee Folder: https://github.com/jenkinsci/job-dsl-plugin/pull/1232

### CODE REVIEW

**Comment by jamietanna** [comment]
Hey thanks for raising this! I'm happy finishing this off, as I've got it mostly working locally, are you happy me pushing to this branch and keeping you as a contributor, or shall I raise a separate PR?

**Comment by jfroche** [comment]
thank you ! do no hesitate for force push here

**Comment by jamietanna** [comment]
Sorry for the late reply, I've just picked this up again.

I've got the core code changes done, but seeing an issue due to:

>    4.212 [seed #1] ERROR: (script, line 1) version 5.14 or later of plugin 'cloudbees-folder' needs to be installed

**Comment by jamietanna** [comment]
Moving to #1251, thanks for the work on this :raised_hands:

**Pull request closed without merging**
