### PR TITLE
Adding failSafeTimeoutDuration to the DSL, includes tests

### PR DESCRIPTION
**Pull request by akomakom**

### CODE REVIEW

**Comment by akomakom** [comment]
I'm wondering now if I should make the new flag a separate closure, ie:

```
void elastic(int percentage = 150, int numberOfBuilds = 3, int minutesDefault = 60)
void elasticFailSafeTimeout(boolean failSafeTimeout = true)
```

This way I can comply with the guidelines for setting booleans to true and there won't be any ambiguity on the **@since** tag since I'm expanding an existing signature.

Anyway, I'll wait for feedback.

**Comment by daspilker** [comment]
These change will break compatibility with versions <1.16, so I can't merge it as it is.

I would prefer one of these options:
1. do not change anything and use the [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL)
2. add a `strategy(Closure closure)` method which would provide all available strategies through the [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL)
3. add a new `elastic(Closure closure)` method which uses a nested context for all elastic timeout options

**Comment by akomakom** [comment]
Thank you for the Automatically Generated DSL link, I haven't looked into it and didn't know that this was an option.  I have it working now with no changes to the plugin, although the BuildTimeoutWrapper constructor necessitated additional arguments:

    wrappers {
        buildTimeoutWrapper {
                        strategy {
                            elasticTimeOutStrategy {
                                timeoutPercentage('300')
                                timeoutMinutesElasticDefault('480')
                                numberOfBuilds('5')
                                failSafeTimeoutDuration(true)
                            }
                        }
                        timeoutEnvVar("") //required by constructor
        }
     }

More flexibility but more work, I guess that's fair.

**Comment by daspilker** [comment]
You could send a PR to the build-timeout plugin to convert the `@DataBoundConstructor` parameter to a `@DataBoundSetter` since those are optional. And you could add some `@Symbol` annotations to get shorter names, e.g. `elastic` instead of `elasticTimeOutStrategy`. See [Struct Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Structs+plugin) for details.

**Comment by daspilker** [comment]
You could send a PR to the build-timeout plugin to convert the `@DataBoundConstructor` parameter to a `@DataBoundSetter` since those are optional. And you could add some `@Symbol` annotations to get shorter names, e.g. `elastic` instead of `elasticTimeOutStrategy`. See [Struct Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Structs+plugin) for details.

**Pull request closed without merging**
