### PR TITLE
TestNG and CI Game plugins support

### PR DESCRIPTION
**Pull request by noroutine**
This adds support for publishing TestNG results with testng-plugin, as well as support for CI game plugin

### CODE REVIEW

**Comment by daspilker** [comment]
Please open separate pull requests for each feature (aka plugin support) and squash your commits to a single one (per feature).

**Comment by daspilker** [comment]
Are you interested in picking this up? Otherwise I will close the pull request.

**Comment by daveLC** [comment]
I'd really like the testng addition in there, can you split this as suggested and resubmit?

**Comment by daspilker** [comment]
@daveLC can you do it?

**Comment by daveLC** [comment]
@daspilker Yes, can do. What shall I do about the documentation changes?

**Comment by daspilker** [comment]
Rebase the changes to the current master branch, add GroovyDoc for each new DSL method and add an example. See [CONTRIBUTING.md](https://github.com/jenkinsci/job-dsl-plugin/blob/master/CONTRIBUTING.md), there is a check list for pull requests at the bottom.

**Comment by daveLC** [comment]
I have created a new pull request for the TestNG only code:
https://github.com/jenkinsci/job-dsl-plugin/pull/642

**Pull request closed without merging**
