### PR TITLE
Add support for extracting related JIRA environment variables

### PR DESCRIPTION
**Pull request by arhohuttunen**
The JIRA plugin support was missing this feature implemented in version 2.2 of the plugin.

### CODE REVIEW

**Comment by arhohuttunen** [comment]
Since I'm still unable to login to Jenkins JIRA to create an issue I'll elaborate on this pull request a bit more.

Typical usage:

1. Add this build step
2. Use the _Progress JIRA issues by workflow action_ or _Move issues matching JQL to the specified version_ with JQL like:
`issue in (${JIRA_ISSUES})`

This allows us to handle only JIRA issues related to the change set.

**Comment by arhohuttunen** [comment]
Also, for anyone interested there is a workaround for current vesion. Add this in your job:

```
configure { project ->
    project / prebuilders << 'hudson.plugins.jira.JiraEnvironmentVariableBuilder'(plugin: 'jira@2.2.1')
}
```

**Comment by daspilker** [comment]
Look good. Please squash your commits to a single one.

**Comment by arhohuttunen** [comment]
Done.

**Pull request merged**
