### PR TITLE
Jenkins 32502

### PR DESCRIPTION
**Pull request by bengineer-**
* Added support for HipChat Plugin v1.x
* Note that I removed support for previous version, rather than trying to support both

### CODE REVIEW

**Comment by daspilker** [comment]
You need to fix the build problems. Run `./gradlew check` locally to see what went wrong.

DSL compatibility is a major concern. You need to keep compatibility with older versions. But support for older versions can be marked as deprecated to be removed eventually.

**Comment by daspilker** [comment]
I'm closing this because the upcoming generic DSL will work for newer version of the HipChat plugin.

**Comment by bengineer-** [comment]
I've upgraded to the latest build, but cannot get your new generic DSL to work:

`
hipChatNotifier {
                                    room(hipChatRooms)
                                    matrixTriggerMode('ONLY_PARENT')
                                    startJobMessage('Start')
                                    completeJobMessage('Complete')
                                    notifications {
                                        notificationConfig {
                                            notifyEnabled(true)
                                            textFormat(false)
                                            notificationType('STARTED')
                                            color('YELLOW')
                                            messageTemplate('My message')
                                        }
                                    }
                                }
                            }
`

And this gives the error:
`
ERROR: (JobCreator.groovy, line 421) No signature of method: javaposse.jobdsl.dsl.helpers.publisher.MavenPublisherContext.hipChatNotifier() is applicable for argument types: (com.host.web.delivery.jenkins.JobCreator$_createJobs_closure5$_closure11$_closure13$_closure14$_closure22$_closure31) values: [com.host.web.delivery.jenkins.JobCreator$_createJobs_closure5$_closure11$_closure13$_closure14$_closure22$_closure31@5cefb8f7]
`

**Comment by daspilker** [comment]
I can't reproduce your problem. This following script is working for me with a build from the current master branch (https://github.com/jenkinsci/job-dsl-plugin/commit/f3d944315ea4baeb7c5ea75a994d38efc032358d).

```groovy
job('example') {
  publishers {
    hipChatNotifier {
      room('my room')
      token(null) // use global config
      matrixTriggerMode('ONLY_PARENT')
      startJobMessage('Start')
      completeJobMessage('Complete')
      notifications {
        notificationConfig {
          notifyEnabled(true)
          textFormat(false)
          notificationType('STARTED')
          color('YELLOW')
          messageTemplate('My message')
        }
      }
    }
  }
}
```

**Comment by socket70** [comment]
The problem is when the room name is stored in a variable (bengineer's example) rather than hardcoded (your's). I'm having the same problem.

**Pull request closed without merging**
