### PR TITLE
[FIX JENKINS-53830] don't persist category

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by calebdelnay** [comment]
I did a build of the plugin with this patch applied to test https://github.com/jenkinsci/configuration-as-code-plugin/issues/253 and the fix worked! Any thoughts on merging and doing a release of the plugin?

**Comment by filipowm** [comment]
Up! I have also tested it, because it blocks me at current stage, and it works. When we could expect release?

**Comment by calebdelnay** [comment]
@daspilker Are you still actively maintaining job-dsl-plugin and, if so, could this PR be merged and a new release cut? It would fix the majorly breaking issue at https://github.com/jenkinsci/configuration-as-code-plugin/issues/253. Thanks!

**Comment by bclouser** [comment]
Any update on this?

**Comment by gtseres** [comment]
This is blocking us as well. @daspilker could we create a new release with this fix?

**Comment by dgarzon** [comment]
@casz @daspilker @jglick @timja any chance this can get merged and released? Thanks!

**Comment by gtseres** [comment]
@timja thanks a lot for approving this! 👍 
Are we also going to merge it and create a new release? Thanks!

**Comment by timja** [comment]
I'm not a maintainer here, it needs @daspilker

**Comment by dgarzon** [comment]
@timja @ndeloof: @daspilker has not been active since around July. Many have attempted to get him to merge and release this, with no response whatsoever. Can we get someone from the Jenkins organization to take care of this? Thank you!

**Comment by gtseres** [comment]
Not sure if @jstrachan or @rawlingsj from the `JenkinsX` project have any idea on who can help here.

**Comment by timja** [comment]
Even if someone were to merge this PR only daspilker has release permissions:
https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/component-job-dsl-core.yml

if he's no longer around then the way forward would be for someone to adopt the plugin:
https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin

**Comment by rawlingsj** [comment]
> Not sure if @jstrachan or @rawlingsj from the JenkinsX project have any idea on who can help here.

Perhaps this plugin is a good candidate to move to the Jenkins X infra which we use to perform CI + release pipelines.  We can build a preview Jenkins image with any proposed changes to the plugin from a PR and deploy to a preview environment to run automated tests and manual verification.  Then upon merge to mater have the automated release pipeline take over to avoid this dependency on individuals to perform manual releases?

**Comment by rawlingsj** [comment]
I'm happy to help set this up next week if folks agree.

**Comment by jglick** [comment]
There is a well-established process for reviewing, merging, and releasing PRs to Jenkins plugins. It “just” requires an official maintainer, which this plugin apparently does not currently have. If anyone is interested in becoming a maintainer, please follow the plugin adoption guidelines.

> deploy to a preview environment to run automated tests and manual verification

Regular `Jenkinsfile`s of course run automated tests. The usual ways to perform manual verification of a plugin PR are:

* Check out the PR locally and `mvn hpi:run`.
* Assuming [JEP-305](https://github.com/jenkinsci/incrementals-tools#enabling-incrementals-the-easy-way) has been activated, which even a non-maintainer can prototype in a PR, download the resulting binary and install into a Jenkins service of your choice.

> upon merge to ma[s]ter have the automated release pipeline take over

There is a longstanding discussion in the Jenkins infrastructure community about how to do releases from trusted infrastructure, but there are complex concerns about interaction with the `maven-release-plugin` versioning scheme, and about the attack surface exposed by various proposals. In the meantime, official releases are done directly by maintainers, with per-user Artifactory credentials restricted to a group/artifact ID namespace. JEP-305 provides an alternative system which deploys automatically to Artifactory but does not currently feed into the traditional update center (there is some work to make “incremental” releases from `master` be fed automatically into Evergreen).

**Comment by rawlingsj** [comment]
Ok but the process kinda sounds a bit broken in the CI/CD world where a single person is required to manually release when we have all this automated along with preview environments with Jenkins X.  I don't mind either way but just trying to help if needed.  I don't mean to step on anyones toes if everything is working fine.

**Comment by jglick** [comment]
Do not get me wrong—no one is happy with the current process for releasing Jenkins plugin updates. I am just saying that the organizational obstacles to having automatic releases from `master` pushes derive from some subtle issues, which JX would not address. Happy to discuss out of band if you are interested.

Anyway physically cutting a release is easy enough; the issue in this plugin is lack of an active maintainer to review and accept PRs, not any technical / infrastructural limitation.

**Comment by rawlingsj** [comment]
ok cool - hopefully there are some areas where JX can be of benefit and I'm totally up for helping out if that's the case.   I'd love JX to provide automated CI and CD for all Jenkins plugins if possible but only if it provides value.

**Pull request merged**
