### PR TITLE
Eliminate bad plugin version check

### PR DESCRIPTION
**Pull request by jeffb-stell**
Jenkins::Tasks::BuildWrapperProxy is the correct class for 0.10 - 0.13 ruby-runtime

### CODE REVIEW

**Comment by jeffb-stell** [comment]
This is for https://issues.jenkins-ci.org/browse/JENKINS-39807

**Comment by cdoughty-r7** [comment]
We are also seeing this issue.  Its breaking jobs that have the RVM plugin and are built with job dsl.  For now we'll use this branch and a custom built version.  

Here's the XML from a job built with job dsl:
```
        <ruby-proxy-object>
            <ruby-object ruby-class="Jenkins::Plugin::Proxies::BuildWrapper" pluginid="rvm">
                <pluginid ruby-class="String" pluginid="rvm">rvm</pluginid>
                <object ruby-class="RvmWrapper" pluginid="rvm">
                    <impl ruby-class="String" pluginid="rvm">2.3.1</impl>
                </object>
            </ruby-object>
        </ruby-proxy-object>
```  
Here's the XML from a job not built with job dsl:
```
     <ruby-proxy-object>
      <ruby-object ruby-class="Jenkins::Tasks::BuildWrapperProxy" pluginid="rvm">
        <pluginid pluginid="rvm" ruby-class="String">rvm</pluginid>
        <object ruby-class="RvmWrapper" pluginid="rvm">
          <impl pluginid="rvm" ruby-class="String">2.3.1</impl>
        </object>
      </ruby-object>
    </ruby-proxy-object>
```

**Comment by daspilker** [comment]
See my comment on [JENKINS-39193](https://issues.jenkins-ci.org/browse/JENKINS-39193?focusedCommentId=282560&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-282560).

**Comment by cdoughty-r7** [comment]
Adding more detail here for future reference.  

The symptoms we saw without this patch were that many (nearly all) of our jobdsl jobs were missing lots of objects and the jobs were completely unusable.

For example a jobdsl job where we had set the label on a job would have the label field checked when rendered but the value for the label would be empty.   In several other cases, values that we'd set in the jobdsl config were just not even populated after rendering, such as custom config files or the ruby rvm.

We're now using a fork of this patch to completely work around the issue: https://github.com/rapid7/job-dsl-plugin/commits/master

**Comment by daspilker** [comment]
I merged this since it works for 0.12. Support for version <= 0.11 is deprecated and will be removed soon.

**Pull request merged**
