### PR TITLE
Add Join Trigger on publishers

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by nithril** [comment]
:+1:

**Comment by camiloribeiro** [comment]
In case you ended up here before this pr is merged:
https://gist.github.com/camiloribeiro/d5377ea528952558267a

**Comment by daspilker** [comment]
The pull request needs to have documentation and tests before it gets merged.

**Comment by camiloribeiro** [comment]
@daspilker I will support on that, next week. :)

**Comment by diorcety** [comment]
@camiloribeiro thanks, i haven't time these days for that.

**Comment by daspilker** [comment]
Replaced by #518.

**Pull request closed without merging**
