### PR TITLE
[JENKINS-30493] added support for global Maven settings

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by KostyaSha** [comment]
:+1:

**Comment by KostyaSha** [comment]
FYI you can comment in commit message/title [FIXED JENKINS-30493] and issue in jira will be automatically closed.

**Comment by KostyaSha** [comment]
Do you plan to do new release? As i see your commits are very good for doing periodic releases.

**Comment by daspilker** [comment]
I try to do a release roughly every 4 weeks. The next one will be in the first week of October.

**Comment by KostyaSha** [comment]
Sound too long...

**Pull request merged**
