### PR TITLE
[JENKINS-37422] fixed compatibility with Ruby Runtime Plugin

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by daspilker** [comment]
@sheehan I did some changes on the API viewer in https://github.com/jenkinsci/job-dsl-plugin/pull/906/commits/03d8d70cb886dfa5689fbeb537648fa6fb3985f7 to support multiple plugins per signature. Can you have a look?

**Comment by sheehan** [comment]
👍 looks good to me

**Comment by daspilker** [comment]
@sheehan thanks for the review!

**Comment by fatmcgav** [comment]
Any chance of getting a release with this fix in? 

Cheers

**Pull request merged**
