### PR TITLE
add support for the slack plugin

### PR DESCRIPTION
**Pull request by sheehan**

### CODE REVIEW

**Comment by ccarpita** [comment]
+1 please, this.

**Comment by gambrose** [comment]
+1

**Comment by daspilker** [comment]
The custom commit message is not available in 1.7. Either increase the minimum version or remove the option. If you keep the option, remove the includeCustomMessage option. It should be automatically set then setting the message,

**Comment by sheehan** [comment]
thanks. updated and rebased

**Comment by tovbinm** [comment]
Is this thing working at all?!

**Comment by sheehan** [comment]
Its working for me

**Comment by tovbinm** [comment]
are you using the latest slack plugin `2.0.1`? @sheehan

**Comment by sheehan** [comment]
@tovbinm no i'm on 1.8

**Comment by tovbinm** [comment]
@sheehan hmm, ok. I just rolled back to `1.8.1` and it works. Thanks.

**Comment by daspilker** [comment]
@tovbinm version 2.x seems to use an incompatible config format, please file an issue: https://issues.jenkins-ci.org/browse/JENKINS/component/16720/

**Pull request merged**
