### PR TITLE
[JENKINS-29801] Add support for BinaryFileParameterFactory

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by daspilker** [comment]
Please add some tests.

**Comment by misery** [comment]
Added some checks and updated "since" version

**Comment by misery** [comment]
Is it ok or should I add some more Factories of it? :-)

**Comment by daspilker** [comment]
It's OK. I'm going to do some refactoring first, because the DSL shares the same implementation for the parameterized trigger build step and the parameterized trigger publisher. But some options, like the factories are only available for the build step and others are only available for the publisher. I will split the implementation and integrate your changes afterwards. But it may take some time.

**Comment by daspilker** [comment]
Replaced by #573. I had to rewrite this after the refactoring (#572).

**Comment by misery** [comment]
No problem! Thank you!!

**Pull request closed without merging**
