### PR TITLE
Add support for Bitbucker pull request builder plugin

### PR DESCRIPTION
**Pull request by mgrebenets**
Add support for [Bitbucket pull request builder plugin](https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+pullrequest+builder+plugin). 
Code is very similar to support got [GitHub pull request builder](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin).

Related to the following JIRA ticket: https://issues.jenkins-ci.org/browse/JENKINS-26488.
And to this [Google Group question](https://groups.google.com/forum/#!topic/job-dsl-plugin/9fOk3dF1mSo).

### CODE REVIEW

**Comment by daspilker** [comment]
This encourages users to store their BitBucket password in plain text in the DSL script. That's not a great idea. We should wait until [JENKINS-24707](https://issues.jenkins-ci.org/browse/JENKINS-24707) got fixed and then add the DSL support.

**Comment by mgrebenets** [comment]
Where should I look for reference to add credentials support to Bitbucket PR builder?
As I understand GitHub PR builder uses credentials, so that might be a good place to look, is it right?

**Comment by daspilker** [comment]
Have a look at the [Credentials Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin) which provides the framework. And have a look at plugins using the Credentials Plugin, e.g. the Git Plugin. Others are listed on the wiki page of the Credentials Plugin. The GitHub Pull Request Builder Plugin can only handle one account which is stored in the global Jenkins configuration and does not use the Credentials Plugin, so IMHO that's not a good example.

**Comment by mgrebenets** [comment]
Thanks for the tip, the Git plugin feels like the right place to look.
I'll close this one for now until I have more secure solution.

**Pull request closed without merging**
