### PR TITLE
adding support for specifying icons for folders

### PR DESCRIPTION
**Pull request by jskjons**
See: JENKINS-27512

### CODE REVIEW

**Comment by daspilker** [comment]
How can I test this? Does this require an additional plugin?

**Comment by jskjons** [comment]
The CloudBees Folders plugin is necessary to test it since this is to customize the icon for the folder.

**Comment by daspilker** [comment]
Yes, but only "Default Icon" is selectable.

**Comment by jskjons** [comment]
Sorry for the confusion, I realize now the icon selection is only available in the Folder Plus plugin with the CloudBees Enterprise. This makes actually testing more annoying since you have to have a valid license or an eval but I definitely it works on our instance.

**Comment by daspilker** [comment]
Sorry, but I will not merge anything which requires a commercial license for testing.

**Pull request closed without merging**
