### PR TITLE
Add issuesTotalColumn() for warnings-ng

### PR DESCRIPTION
**Pull request by nhojpatrick**
So this;
```
listView('releases') {
	...
	columns {
		...
	}
	configure { view ->
		view / columns << 'io.jenkins.plugins.analysis.core.columns.IssuesTotalColumn' {
			name('# Issues')
			type('TOTAL')
		}
	}
}
```

Can change to this;
```
listView('releases') {
	...
	columns {
		...
		issuesTotalColumn()
	}
}
```

### CODE REVIEW

**Comment by nhojpatrick** [comment]
No idea how to update the ListViewSpec so it handles optional parameters.

**Comment by nhojpatrick** [comment]
@quidryan @andrewharmellaw @daspilker are you able to review and give feedback regarding how i need to fix the tests...

**Comment by nhojpatrick** [comment]
@jenkinsci/code-reviewers or are you able to review?

**Comment by TobiX** [comment]
I thought extending this was obsolete (see https://github.com/jenkinsci/job-dsl-plugin/wiki/Extending-the-DSL), since the plugin should expose dynamic DSL (see https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL)? Does that not work?

**Pull request closed without merging**
