### PR TITLE
dsl api documentation

### PR DESCRIPTION
**Pull request by sheehan**
This PR adds the initial implementation of the auto-generating documentation. 
demo: http://sheehan.github.io/job-dsl-plugin/

Steps for publishing the docs:

1. Run ```./gradlew generateApiDoc``` 
   * This will create a JSON file in `/job-dsl-plugin-viewer/data/dsl-<version>.json`
2. Add the version to the select at `/job-dsl-api-viewer/index.html` if not already there
3. Run `./gradlew :job-dsl-api-viewer:publishGhPages`

The generator will use JavaDoc for the method documentation. For longer docs, you can create a markdown file in `job-dsl-core/api-docs/` instead. I've moved a few docs there from the wiki so far.

### CODE REVIEW

**Comment by sheehan** [comment]
any thoughts on this @daspilker ?

**Comment by daspilker** [comment]
Sorry, my Job DSL time went into the preparation of my JUC talks.

Why is this 56K LOC? Why is the framework larger than the content?

**Comment by sheehan** [comment]
Most of that is from `update-center.json`, which i copied from http://updates.jenkins-ci.org/update-center.json. That's used to get plugin metadata. We can link to it directly, but I noticed that it hangs sometimes.

**Comment by daspilker** [comment]
The update-center.json should be fetched at runtime. The infrastructure is unstable, but in that case I can't cut a release because other parts of the infrastructure may also be unavailable. And I would probably need to update the file before each release to get the latest plugin infos.

**Comment by sheehan** [comment]
So you're saying you want to link directly to jenkins-ci.org?

**Comment by daspilker** [comment]
Not necessarily, but it could be a build artifact which could be downloaded a build time. And what about `job-dsl-api-viewer/dist` and `job-dsl-api-viewer/src/vendor`? Aren't those build artifacts as well?

**Comment by sheehan** [comment]
Which build do you mean? "Fetch the latest update-center.json" could be an item in the steps above. `job-dsl-api-viewer/dist` is an artifact of the grunt build. But you only need to run the grunt build if you make changes to the website code.

**Comment by daspilker** [comment]
I would like to avoid checking in any non-source artifacts to avoid a mismatch between the source artifacts and generated artifacts. That includes `data/update-center.jsonp`, `dist` and `src/vendor`. How about adding a Grunt/Gulp plugin to the Gradle build to run the Grunt/Gulp build when running the `generateApiDoc` and/or `publishGhPages` tasks (or a separate new task)?

Apart from the details, what would be the general plan to migrate to the API viewer? Do we still need the wiki? Do we need to maintain the docs for the wiki and the viewer in parallel? And for how long? When and how do we fill in the necessary Groovy docs?

**Comment by sheehan** [comment]
I see the benefit in having a gradle call that pulls down the latest `update-center.jsonp`.

I checked in the generated artifacts into `dist` so that anyone can run the doc page locally without having to install npm/gulp and build it. The way it is now, the only time anyone has to do a gulp build is if they change something with the web src, which would probably be rare.

I'm not sure what you mean with artifacts in `src/vendor` because that's just third party libs included in the `index.html`.

For migration I think it might be best to start after the next release is cut. I can move the existing wiki info over and I don't think it'll take that long. Its just a matter of moving the larger items to `job-dsl-core/api-docs/` and everything else inline. It should easily be done by the time we want to finalize that release.

**Comment by daspilker** [comment]
I sent you a PR with a proposal for the Gradle/Gulp changes that I had in mind, see https://github.com/sheehan/job-dsl-plugin/pull/1.

I'm not a huge fan of a big bang change. I would like to concentrate in the job/view/folder reference pages first, get that right and then think about the rest. IMHO the reference page are currently the biggest pain point because the job reference page is huge and the code examples get scrollbars if they exceed a width of 78 chars.

But let's get the build stuff done at first.

**Comment by sheehan** [comment]
sounds good

**Comment by sheehan** [comment]
is this ready to merge then?

**Comment by daspilker** [comment]
I want to review the JSON generator and fiddle with moving the docs to the class level GroovyDoc instead of using markdown files. So the docs will be available in an IDE and the API viewer. But I need to check if I can reuse the GroovyDoc generator classes for that. It may take some time.

**Comment by sheehan** [comment]
Yeah i wasn't thrilled with having external files, but having detailed docs with html and multiple examples in the method javadoc also seems like a pain. How would you do it at the class level?

**Comment by daspilker** [comment]
OK, code blocks in javadoc is a pain. But I still want the text to be there on method level for IDE support. How about moving the examples to external files and the text to javadoc? The examples would be plain DSL scripts with one or more job definition (or whatever). As a bonus we can add a test suite which runs the examples to verify them.

**Comment by sheehan** [comment]
Good idea. How do you want to reference them from a method? Using a naming convention (like it is now) or maybe having an annotation the takes the path(s) as a value?

**Comment by daspilker** [comment]
I like the naming convention, an annotation on many DSL methods would cause clutter.

**Comment by sheehan** [comment]
I've updated http://sheehan.github.io/job-dsl-plugin/ with the latest. I added your changes and made the updates we discussed in the other PR. I removed the markdown reader dependency since we only had the one markdown file left, and moved it to a .hbs file. I also updated the context methods so that they appear within the method signature if you click on the expand button. I have a few more tweaks and some cleanup to do, but I should get to that in the next few days.

**Comment by daspilker** [comment]
Nice!

I noticed that the syntax highlighting is not working correctly. E.g. on http://sheehan.github.io/job-dsl-plugin/#path/queue the language auto-detection seems to choose Ruby rules, it adds a ruby class to the pre element `highlight groovy hljs ruby`. I tried updating highlightjs to 8.7 and configure the auto detection (http://highlightjs.readthedocs.org/en/latest/api.html#configure-options) but neither helps. Maybe the code snippets have to wrapped with a `code` element as in the examples (https://highlightjs.org/usage/)?!? But that's only a minor issue an can be solved later.

**Comment by daspilker** [comment]
I started to add GroovyDoc and examples for the view reference. I'm really looking forwards to launch the API viewer!

But I found some more issues:
* Inner enums are shown with a dollar sign, e.g. `statusFilter(javaposse.jobdsl.dsl.views.ListView$StatusFilter filter)`. Can you change the dollar sign to a dot since that's for syntax to be used by users for importing etc?
* Tags are visible in Inline comments with markup, e.g. `// Upload the stream as <a href="https://wiki.jenkins-ci.org/display/JENKINS/User+Content">user content</a>.` Can you remove the tags for inline comments?

**Comment by sheehan** [comment]
Ok I've fixed those two issues. Also I'm not sure why that `ruby` class pops up, but I added a line to remove it for now.

Did you want me to rebase this branch?

**Comment by daspilker** [comment]
Great! Yes, please rebase and force push the branch.

I noticed another issue. Example from methods in `ViewFactory` are not picked up. I tried to place them in a `ViewFactory` and in the `DslFactory` folder, but neither works.

I hope that my issue reporting does not sound like complaining. I :heart: the API viewer.

**Comment by daspilker** [comment]
Ah, scratch the last issue. Don't know what went wrong, but it's working now.

**Comment by sheehan** [comment]
No worries :) It's good you're catching these issues now. Latest PR is merged and the branch is now rebased.

**Comment by daspilker** [comment]
Very nice!

I tested the search feature. To go back to the tree navigation, a user must delete the search text. Can you add a button or something like that to go back to the navigation? Or is there another way to go back? And what's the purpose of showing the plugins in the search results? Clicking on a plugin has no effect and then I thought the results are grouped by plugin, but that does not seem to be the case.

There are 3 TODOs left in the API generator. Can you add the minimumVersion to the JSON and display the value in the viewer? The plugin ID is stored on method level in the JSON, but I think the version should be on signature level. There can be a signatures `foo(String a)` and `foo(String a, String b)` with different minimumVersion versions because option b has been added in a later version. I don't mind if you remove the other 2 TODOs, we can deal with that later when necessary.

When adding the examples, I did a lot of copy&paste of examples for inherited methods. See the `configure.groovy` files for each view type. On one hand I wanted the example to show the selected view type, but on the other hand doing lots of copy&paste seems to be wrong. And the job types have a lot more inherited options... It's OK for now, but do you have an idea for solving this?

**Comment by daspilker** [comment]
I implemented one of the remaining TODOs in the API generator. Examples will now be resolved from super classes as well. See https://github.com/sheehan/job-dsl-plugin/pull/6.

I'm working on migration the job reference, there is still plenty of time left until my planned release date. I will not copy&paste the examples for common job options, so the example from the Job class will be used. The current reference also shows the examples for free style jobs, so it's OK for the API viewer.

There are a lot of enums in the DSL and I started to describe the enum values in the GroovyDoc, but that seems to be wrong. Can you make the enums clickable so that they show their options, e.g. with a new detail page for enums?

**Comment by sheehan** [comment]
> I tested the search feature. To go back to the tree navigation, a user must delete the search text. Can you add a button or something like that to go back to the navigation?

I'll add an X button to clear the search.

> Clicking on a plugin has no effect 

There was a bug. Should be fixed now. It's supposed to show the plugin name, description, and list of DSL methods.

> Can you add the minimumVersion to the JSON and display the value in the viewer?

:+1: 

> Can you make the enums clickable so that they show their options

:+1: 

So three things on my todo list. I should get to them in the next couple of days.

**Comment by daspilker** [comment]
Cool.

I made some progress with migrating the job reference. Now I "only" need to migrate the wrappers, steps, publishers and build parameters until it's done. I published a snapshot to http://daspilker.github.io/job-dsl-plugin/.

I noticed that the plugin links are missing for the top-level methods. That's because of my idea to use DslFactory as a starting point for the generator. I will try to move the @RequiresPlugin annotations to the interface and change the AST to look at the interface as well.

I used some internal links (`@link` tag), see http://daspilker.github.io/job-dsl-plugin/#path/userContent. They are currently broken. Is there a chance to fix that?!?

**Comment by daspilker** [comment]
I have to add two more items to your todo list.

Have a look at https://sheehan.github.io/job-dsl-plugin/#path/job-steps-copyArtifacts. The methods with more than two parameters use a different closure type than the method with two parameters. But when expanding the closures, the same contexts are shown. The JSON is correct, so it seems to be a display problem.

When using a link that points to a deeply nested context, the contexts are correctly expanded in the navigation tree, but the relevant context may not be visible and the user has to scroll to find it. Can the navigation be scrolled so that the context is visible? And can you highlight the selected context in the navigation? Sometimes is hard to find the selected context.

**Comment by sheehan** [comment]
> The methods with more than two parameters use a different closure type

Ugh :( I didn't know about that. Currently the tree and the url format assume one context per method name. I'll take a look at changing that.

**Comment by sheehan** [comment]
I'm thinking of adding method signature info to the url path like:

`http://localhost:8080/#path/job(String,Closure)-steps(Closure)-copyArtifacts(String,Closure)-flatten`

so we can follow contexts by signature. But I'm not sure what to do about the tree. I would have to list out each signature, I think.

**Comment by daspilker** [comment]
Hm, right, I haven't thought about the tree and the URL format. That sounds like fundamental changes. I like the URL path with the signatures, but the tree will be crowded if each signature is shown. I could probably live with a temporary solution since the problem will go away when the deprecated copyArtifacts methods are removed.

I migrated everything except for most of the publishers. I hope that there are no more corner cases.

**Comment by daspilker** [comment]
I like the diff stats: +4,227 −7,946. Better documentation with fewer lines!

I have two items left on my todo list. ViolationsContext uses methodMissing to implement a lot of methods and those do not show up in the docs. I will change the context to use explicit methods. And I will remove the instructions for the old docs from CONTRIBUTING.md since the migration is complete.

**Comment by sheehan** [comment]
Awesome! 

I'll push out fixes for my remaining issues tonight or tomorrow.

**Comment by sheehan** [comment]
I've added a clear search button, fix for copyArtifacts, and the highlight/scroll of the selected tree node.

I spent a long time working on adding the method signatures to the url path, but ended up shelving that for now as I couldn't figure out how to make it work properly with the (non-signatured) tree.

I still need to add the min plugin version and the enum page. I should be able to get to that tomorrow.

**Comment by daspilker** [comment]
Nice work!

The buildSelector closure within copyArtifacts is not expandable. Can you have a look at that?

```
copyArtifacts(String jobName) {

    // Selects the build to copy artifacts from.
    buildSelector(Closure selectorClosure) 
```

**Comment by sheehan** [comment]
For some reason the closure param in CopyArtifactContext#buildSelector isn't getting a DelegatesTo annotation. If I explicitly add one it works.

**Comment by daspilker** [comment]
OK, thanks for your analysis, I will have a look.

**Comment by sheehan** [comment]
I've added the minimum version above the signature. I also listed the enum options below the signature doc. It would probably be best to have the enum as a separate page as you mentioned, with documentation for each value, but this should help for now.

**Comment by daspilker** [comment]
Awesome. I updated the GroovyDoc to not list the enum options. I think we are ready to go for the next release, so I merged the branch. If you want to do some tweaks, just open a new pull request.

This was probably the biggest PR ever for the job-dsl-plugin with 50 commits! And probably also the one that took the longest to get merged. Sorry about that, but I did not have any time until my parental leave in July/August to work on this.

**Comment by sheehan** [comment]
:+1: 

Thanks for all the feedback and for migrating those docs.

**Comment by daspilker** [comment]
I pushed the first changes for 1.39 (`BuildParametersContext.listTagsParam`). When I toggle the version selector, the detail view does not change. Can you have a look at that?

**Pull request merged**
