### PR TITLE
add separate methods for each job, view, configFile type.

### PR DESCRIPTION
**Pull request by sheehan**
Added new methods to JobParent as discussed in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/job-dsl-plugin/2-iuHl4tidI/iPkiYTYnkQ4J

```groovy 
FreeStyleJob freeStyleJob(String name, @DslContext(FreeStyleJob) Closure closure)

BuildFlowJob buildFlowJob(String name, @DslContext(BuildFlowJob) Closure closure)

MatrixJob matrixJob(String name, @DslContext(MatrixJob) Closure closure)

MavenJob mavenJob(String name, @DslContext(MavenJob) Closure closure)

MultiJob multiJob(String name, @DslContext(MultiJob) Closure closure)

WorkflowJob workflowJob(String name, @DslContext(WorkflowJob) Closure closure)

ListView listView(String name, @DslContext(ListView) Closure closure)

SectionedView sectionedView(String name, @DslContext(SectionedView) Closure closure)

NestedView nestedView(String name, @DslContext(NestedView) Closure closure)

DeliveryPipelineView deliveryPipelineView(String name, @DslContext(DeliveryPipelineView) Closure closure)

BuildPipelineView buildPipelineView(String name, @DslContext(BuildPipelineView) Closure closure)

BuildMonitorView buildMonitorView(String name, @DslContext(BuildMonitorView) Closure closure)

ConfigFile customConfigFile(String name, @DslContext(ConfigFile) Closure closure)

ConfigFile mavenSettingsConfigFile(String name, @DslContext(ConfigFile) Closure closure)
```
I've updated the docs to reflect this. While doing so, I moved some API info from the main page to the details page to avoid a bunch of duplication.

### CODE REVIEW

**Comment by daspilker** [comment]
Nice, this will be included in 1.30. I have no idea how to do a code review for this change, but I will figure it out.

**Comment by daspilker** [comment]
I made a few refactorings, did some work on the docs and moved the tests for `Job` back to `JobSpec`.

Please have a look at https://github.com/daspilker/job-dsl-plugin/commits/separate_type_methods and cherry-pick my commits to your branch to update the pull request.

I'm not sure what to do with `MavenJob#steps()`. The problem also exists for the workflow job which has no steps, wrappers and publishers. Ideally those methods should be moved to intermediate classes, but I could not come up with good names for "JobWithSteps" or "JobWithPublishersAndWrappers". I had a look at the Jenkins class hierarchy but Project extends AbstractProject extends Job is not great either. :confused:

**Comment by sheehan** [comment]
Those changes look good to me, thanks. 

Yeah, I'm not sure about the MavenJob#steps problem either. Maybe we could use Traits for that if the Groovy version ever gets updated?

**Comment by sheehan** [comment]
Also, I've been working on the auto-generated docs a bit (latest demo [here](http://sheehan.github.io/job-dsl-plugin)). I think this was the last barrier for that, so once it's merged I'll update the email thread with details of the proposal.

**Comment by daspilker** [comment]
Cool! And yes, traits would be great to have. I tried to lobby for an Groovy update (https://issues.jenkins-ci.org/browse/JENKINS-21249, https://github.com/jenkinsci/jenkins/pull/1085), but progress stalled.

**Comment by sheehan** [comment]
Not sure why that build failed. Some dependency resolution failure.

**Pull request merged**
