### PR TITLE
Updated documentation about support for cucumber-reports plugin

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by daspilker** [comment]
This PR does not just update the documentation. What is the intention of this PR?

**Comment by damianszczepanik** [comment]
I've added support for DSL and updated code that refers to the newer version. I wanted to make https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.cucumberReports updated

**Comment by damianszczepanik** [comment]
@daspilker any comment about this PR?

**Comment by daspilker** [comment]
This breaks compatibility for users who are using an older version of the Cucumber reports plugin.

From what I see in this PR, the latest version does not seem to have much in common with the version supported by Job DSL. In this case I suggest to deprecate the built-in DSL support for the Cucumber reports plugin and to use the [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL) for newer versions.

    job(String name) {
      publishers {
        cucumberReportPublisher {
          jsonReportDirectory(String value)
          fileIncludePattern(String value)
          fileExcludePattern(String value)
          failedStepsNumber(int value)
          skippedStepsNumber(int value)
          pendingStepsNumber(int value)
          undefinedStepsNumber(int value)
          failedScenariosNumber(int value)
          failedFeaturesNumber(int value)
          buildStatus(String value)
          classifications {
            classification {
              key(String value)
              value(String value)
            }
          }
          parallelTesting(boolean value)
          trendsLimit(int value)
        }
      }
    }

**Comment by damianszczepanik** [comment]
This is what I've done but still API Viewer displays old API. I don't want to present outdated API as the most recent API and would like to encourage users to update the plugin and use new features.

What should I do (except ``@DataBoundConstructor`` annotation to make API Viewer updated?

**Pull request closed without merging**
