### PR TITLE
JENKINS-66189 Use dynamic DSL instead of outdated PostBuildScript syntax

### PR DESCRIPTION
**Pull request by dheid**
Hi @daspilker!

A user complained in https://issues.jenkins.io/browse/JENKINS-66189 that his Job DSL generated PostBuildScript configuration fails. That's because I removed some deprecated configuration options in version 3.x and forgot that there is a non-dynamic DSL in the Job DSL plugin.

To be sure, no one uses the old syntax any longer, please let us remove the entries from the Job DSL plugin. I removed them in this pull request.

Best regards

Daniel

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dheid** [comment]
@jamietanna Ping

**Comment by dheid** [comment]
@daspilker I think it's a good think to remove the old PostBuildScript stuff. It damages the configuration of the users.

**Comment by dheid** [comment]
@jamietanna Are you there?

**Comment by dheid** [comment]
@jamietanna How are you doing?

**Comment by jamietanna** [comment]
Hey @dheid thanks for this, this looks like a reasonable change. Just to confirm, have you seen if the Dynamic DSL picks up all the options for the plugin that we'd want?

**Comment by dheid** [comment]
@jamietanna Yes, it includes everything

**Pull request merged**
