### PR TITLE
Add missing options for Parameterized Remote Trigger Plugin

### PR DESCRIPTION
**Pull request by jsmrcka**
https://issues.jenkins.io/browse/JENKINS-68781

### CODE REVIEW

**Comment by rsvoboda** [comment]
@jsmrcka, is @jamietanna the one we want feedback from?

**Comment by jamietanna** [comment]
Yes it is, I'll get round to it when I get a chance

**Comment by rsvoboda** [comment]
ok, thank you

**Comment by jsmrcka** [comment]
> Just to confirm, these aren't picked up by the Dynamic DSL?

Good point: `disabled` is picked up, the others are not. I'll update (and rebase) the PR.

**Comment by jsmrcka** [comment]
@jamietanna Could we have the final review, please? See my previous comment.

Also, how soon can this be released?

**Review by jamietanna — APPROVED** [review]

**Comment by jamietanna** [comment]
Tagged, released and should be live shortly :+1:

**Pull request merged**
