### PR TITLE
Add support for Pipeline Aggregator View

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by kamilszymanski** [comment]
@daspilker is there anything missing in this PR?

**Comment by kamilszymanski** [comment]
@jamietanna could you take a look at this PR?

**Comment by jamietanna** [comment]
Sorry for the late reply. To confirm, does the Dynamic DSL not work for this?

**Comment by kamilszymanski** [comment]
Unfortunately dynamic DSL supports only generic view properties 
dynamic-dsl

**Comment by jamietanna** [comment]
FYI I've just been looking at this, but due to https://issues.jenkins.io/browse/JENKINS-67157 I'm unable to test it locally. I'll try downgrading the plugin and giving it a go in the meantime

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
