### PR TITLE
[JENKINS-32924] Add LogRotator to Workflow Multibranch

### PR DESCRIPTION
**Pull request by meip**
Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-32924

Add a LogRotator to Workflow Multibranch Jobs to rotate build artifacts.

### CODE REVIEW

**Comment by daspilker** [comment]
Sorry for the late feedback. I'm running Jenkins 1.625 with Pipeline Multibranch 1.14 and Branch API 1.7. I can't find a setting for the strategy in the UI. What do I need to do to test this? Or has this become obsolete?

**Comment by daspilker** [comment]
I made the {{BranchSourcesContext}} extensible (see https://github.com/jenkinsci/job-dsl-plugin/pull/846) so that it will work with the [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL). The embedded API viewer shows several options for {{strategy}}, but the UI does not show any strategy.

**Comment by meip** [comment]
I think this property is gone from the "root" config and should better be configured via Pipeline script. The Pipeline Multibranch is a bit messed up with properties inherited to branches. See discussion here: 
https://issues.jenkins-ci.org/browse/JENKINS-30519
https://issues.jenkins-ci.org/browse/JENKINS-34005

An example to do it within Jenkinsfile is here: https://github.com/jenkinsci/workflow-multibranch-plugin/blob/master/src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java

As you can see there should also be an option to set it with the *Config File Provider Plugin*. 

Considering these two options, and your remarks that it is no more possible to configure logRotation for Multibranch via Gui, I don't know if we should purge this PR?

**Comment by daspilker** [comment]
Ah, thanks for the pointers. Since logRotator is supposed to be configured in Jenkinsfile and not on the multi-branch job, I'm closing this PR.

**Comment by ianfixes** [comment]
How can I confirm whether this feature is currently working?  What behavior should I see?

I'm using the Scripted Pipeline (`Jenkinsfile`-based), and my pipeline has builds that are months old.  I've just added the following to the very top of the `Jenkinsfile`:

```groovy
 properties([
  buildDiscarder(logRotator(daysToKeepStr: '4', numToKeepStr: '4',
                            artifactDaysToKeepStr: '4', artifactNumToKeepStr: '4'))
])
```

A pull request build with this file in it has completed successfully, and there seems to be no effect whatsoever -- no error message is printed, no success message is printed, and most importantly, I still have a few months worth of builds in this pipeline.

What am I doing wrong?  When does the log rotation / deletion actually happen?  How can I read back the properties I'm trying to apply, to see that they've actually taken effect?

Where are the accurate-as-of-2019 docs on this feature?

**Pull request closed without merging**
