### PR TITLE
JENKINS-21750 DSL support for the promoted-builds plugin (take 2 for #157)

### PR DESCRIPTION
**Pull request by steve-jansen**
Hi @dickerpulli and @daspilker 

This is my humble attempt to help the project ship Thomas' awesome work in #157.  I fully understand the motivation to create extension points in the DSL for other plugins in the future.  Thomas' work is solid - I've been using a local .hpi build of his PR branch for many weeks now.  It's been very reliable.  

I think the Jenkins community overall would benefit quite a bit by shipping #157 as-is, and refactor the promoted-builds support in a separate PR for an extension point.  The work on the extension point seems to have stalled out (no criticism - it's a heroic effort to do both the promoted builds and abstract that support to something generic at the same time).

In an effort to make help make you life easier as the maintainer of the project (and author of the original PR), I did a few things:
1) rebased from the latest upstream master for v1.25 (this was no fun, thanks to @thommay for the first rebase back in July)
2) squashed Thomas' work down to a single commit (maintaining Thomas as the author of course)
3) added a small fix for parameterizedBuild actions in promotions

I hope you find this useful.  The promoted-builds plugin can be a workhorse for continuous delivery in Jenkins, and the job-dsl plugin makes continuous delivery way easier to implement in Jenkins compared to point and click manual job creation in the UI.  Having proper support for promotions in the job-dsl is a great step forward.

All the tests pass on my local build, however, the rebase was fairly complicated so I welcome some serious scrutiny on the changes.

Cheers,
Steve

### CODE REVIEW

**Comment by denschu** [comment]
Any news here? Would be great, if this will be officially released in the near future :-)

**Comment by dickerpulli** [comment]
@daspilker is still working on get the build process to run. Be patient ... :-)

**Comment by steve-jansen** [comment]
An observation - this PR and it's parent (#157) have been open for one year.

**Comment by daspilker** [comment]
As mentioned above, I'm not going to merge this PR, so I'm closing it now.

**Comment by fractal9** [comment]
Pity this PR hasn't been merged (yet?). At least as interim solution this will be extremely useful (_even_ in case promoted-build DSL code needs a complete re-write with the general solution).

@daspilker, if there's no technical reasons preventing this "continuous" approach, then why not accept the PR for the time being?

Thomas & Steve, thanks a ton for developing and maintaining this!
I'm trying to apply the changes on top of 1.32 now -- unfortunately, there's some merge conflicts. So:

> If there is enough interest, I can try to regularly rebase/release my fork.

This will be great.

Cheers
/alex

**Comment by denschu** [comment]
+1

**Comment by kgaitanos** [comment]
+1

**Comment by lionelve** [comment]
Seems like the [extention points work is done](https://github.com/jenkinsci/job-dsl-plugin/pull/468).
@dickerpulli how's the [job-dsl-promotions-plugin](https://github.com/dickerpulli/job-dsl-promotions-plugin) coming along? 

Thanks.

**Comment by jewes** [comment]
how is it going now?

**Comment by daspilker** [comment]
This has been merged into the Promoted Builds plugin as a Job DSL extension, but the Promoted Builds plugin has not been released yet.

@oleg-nenashev, can you cut a release?

**Pull request closed without merging**
