### PR TITLE
[JENKINS-69849] Add support for additional classpath with seed config

### PR DESCRIPTION
**Pull request by splatch**
Given that CasC have no ways to configure classpath and jenkins bootstrap classpath is isolated from plugins there is no way to actually deliver a shared library to jobdsl beyond pipeline. As described in https://issues.jenkins.io/browse/JENKINS-69849 this approach may double amount of configurations needed to be maintained and complicate basic scenarios.

Provided pull request introduces a new "additionalClasspath" option accepted by seed job configurator which is processed in similar fashion as providedEnv - it is accumulated and passed to lower layers which generate script request and in effect also compile it.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by splatch** [comment]
Not sure how to trigger build again, as failures seem to be unrelated to provided changes.

**Comment by basil** [comment]
Appears to be a failure to implement https://github.com/jenkinsci/job-dsl-plugin/wiki/Real-World-Examples#import-other-files-ie-with-class-definitions-into-your-script.

**Comment by splatch** [comment]
Indeed, this is exactly why this PR was brought to life - to make real world example a real. ;-)

**Review by basil — CHANGES_REQUESTED** [review]
Use case appears to be already covered by https://github.com/jenkinsci/job-dsl-plugin/wiki/Real-World-Examples#import-other-files-ie-with-class-definitions-into-your-script.

**Comment by splatch** [comment]
Sure, it is described in docs, but have you seen it working anywhere? The wiki page you point at says "Note that importing other files is not possible when Script Security is enabled and not using Groovy Sandbox". Groovy sandbox and groovy plugin is, as far I can understand, desired to host other things than constructing jobs. To my limited knowledge about jenkins plugin system groovy sandbox is there to make parts of job defined as groovy script.
I been looking for long time on how to get that wiki page example working. None of classpath locations ever worked for me. And if you look closer, that wiki page does not say where the `utilities/MyUtilities.groovy` file should be located in order to be picked up by job.

When you look at jcasc and initial provisioning of jobs I think there is no way that this real world example will ever work. Seed jobs are initialized in a way which does not utilize other plugins (as far I can understand the code), hence they need explicit configuration of groovy classpath.

**Comment by basil** [comment]
> Sure, it is described in docs, but have you seen it working anywhere?

I have.

> I been looking for long time on how to get that wiki page example working.

I suggest you read https://github.com/jenkinsci/job-dsl-plugin/wiki/Script-Security#groovy-sandboxing.

**Comment by splatch** [comment]
@basil Great, would you be so kind and make an example how necessary jcasc sections look a like so seed jobs could rely on imports from classpath?

I seemed to fail far earlier than ScriptSecurity could become an trouble.

**Comment by splatch** [comment]
Follow up thread for search engines and anyone who runs into same trouble: https://groups.google.com/g/jenkinsci-users/c/fF4hn6Ugjf8/m/A0pyGQ-WDgAJ

**Pull request closed without merging**
