### PR TITLE
JENKINS-38151 - added support for AWSEB Deployment plugin

### PR DESCRIPTION
**Pull request by adamtrousdale**

### CODE REVIEW

**Comment by daspilker** [comment]
You can use the [Automatically Generated DSL]() for this:

```groovy
job('example') {
  steps {
    awsebDeploymentBuilder {
      credentialId('test-cred')
      awsRegion('us-east-1')
      applicationName('bar')
      environmentName('bar-env')
      rootObject('root/object')     
      includes('this')
      excludes('that')
      bucketName('foo')
      keyPrefix('key')
      versionLabelFormat('version')
      zeroDowntime(true)
    }    
  }
}
```

**Comment by adamtrousdale** [comment]
@daspilker magic, thanks

**Comment by adamtrousdale** [comment]
@daspilker one question for future reference, how do I know what value to use where you've used `awsebDeploymentBuilder`? I've tried this on Jenkins and its complaining about `No signature of method`, I assume I've missed something when reading the Automatically Generated DSL doc

**Comment by daspilker** [comment]
The plugin must be installed and then all available syntax is shown in the embedded API viewer, e.g. http://localhost:8080/plugin/job-dsl/api-viewer.

**Comment by adamtrousdale** [comment]
Going to that URI on my Jenkins box results in a 404, can't find anyway to view the api of the plugin

**Comment by daspilker** [comment]
You need to run Job DSL 1.46 or later

**Comment by adamtrousdale** [comment]
@daspilker Thanks

**Pull request closed without merging**
