### PR TITLE
Update permissions based on changes made in matrix auth plugin 3.0

### PR DESCRIPTION
**Pull request by joshiparth1000**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dsrink** [comment]
@joshiparth1000  This looks interesting, I would need exactly that change. Did you see the build errors in testing, would you be able to handle them?

**Review by basil — CHANGES_REQUESTED** [review]
There are (trivial) CodeNarc violations causing the build to fail.

Why is this PR not in draft state when `FolderSpec`, `JobAuthorizationContextSpec`, and `JobSpec` are consistently failing?

What would happen if someone attempted to use Job DSL with the changes in this PR and Matrix Authorization Strategy 2.6.11?

**Comment by jstraw** [comment]
it seems like this change is now either required, or about to be for configuring a Jenkins without getting ambiguous permissions warnings.

**Comment by mickael-ange** [comment]
Hi

I'm not able to configure my job with new dis-ambiguous authorization format introduce in matrix auth plugin 3+.
```
job("dev/devops-ansible-rolling-update-adminsite") {
  disabled false
  authorization {
    permission("GROUP:hudson.model.Item.Build:ec2-dev-v2-adminsite-deployer-only")
    permission("GROUP:hudson.model.Item.Cancel:ec2-dev-v2-adminsite-deployer-only")
    permission("GROUP:hudson.model.Item.Read:ec2-dev-v2-adminsite-deployer-only")
  }
  using "dev/devops-ansible-template"
```

I got the following error when I'm trying to process the new auth perms with Job DSL plugin.

```ERROR: (unknown source) permission must be one of com.cloudbees.plugins.credentials.CredentialsProvider.Create,com.cloudbees.plugins.credentials.CredentialsProvider.Delete,com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains,com.cloudbees.plugins.credentials.CredentialsProvider.Update,com.cloudbees.plugins.credentials.CredentialsProvider.View,hudson.model.Item.Build,hudson.model.Item.Cancel,hudson.model.Item.Configure,hudson.model.Item.Delete,hudson.model.Item.Discover,hudson.model.Item.ExtendedRead,hudson.model.Item.Move,hudson.model.Item.Read,hudson.model.Item.Workspace,hudson.model.Run.Delete,hudson.model.Run.Replay,hudson.model.Run.Update,hudson.scm.SCM.Tag
```
I suppose this PR was aiming to fix this configuration change.

Any chance to resume the progress on this PR?

Thanks

**Comment by eva-mueller-coremedia** [comment]
This is continued in https://github.com/jenkinsci/job-dsl-plugin/pull/1415

**Pull request closed without merging**
