### PR TITLE
Syntax to set multiple ssh agent credentials

### PR DESCRIPTION
**Pull request by keeganwitt**
This is intended to turn DSL like this

```groovy
job('example') {
    wrappers {
        sshAgent('user-a', 'user-b')
    }
}
```

Into XML like this

```xml
<project>
    <com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper>
        <user>user-a</user>
    </com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper>
    <com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper>
        <user>user-b</user>
    </com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper>
</project>
````

### CODE REVIEW

**Comment by daspilker** [comment]
The UI does not allow multiple wrappers of the same type. So the DSL should not generate multiple wrappers of the same type.

See #980.

**Comment by keeganwitt** [comment]
In what version?  1.13 of the SSH Agent plugin on Jenkins 1.642.1 through the UI, generates the XML as I have shown it.

**Comment by daspilker** [comment]
No, the UI generates this:

    <buildWrappers>
      <com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper plugin="ssh-agent@1.13">
        <credentialIds>
          <string>c67a4c07-ea47-4266-94dd-cbab652339e8</string>
          <string>f857a439-2d23-4848-9f1d-17ec5fbccb79</string>
        </credentialIds>
      </com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper>
    </buildWrappers>

**Comment by keeganwitt** [comment]
Oops, you're right.  I was reading the improperly generated XML that the DSL generated before your fix.  Thanks for the quick fix!

**Pull request closed without merging**
