### PR TITLE
add plugin filter. some refactoring.

### PR DESCRIPTION
**Pull request by sheehan**
I thought it might be nice to have the ability to filter out plugins that you don't use, so I added a section on the right that lists the plugins and allows you to include/exclude. See http://sheehan.github.io/job-dsl-plugin. This is stored in localStorage so it should be remembered when you come back. The button on the top-right toggles the plugin list. 

You can also click on each plugin to see its detail page, so I removed that from the search results. 

The JS logic was starting to get a bit complex so I did some refactoring and broke things out into separate files. Still some refactoring and cleanup work to do there, but I'll get to that next. I was hoping to get this in before you do a release.

### CODE REVIEW

**Comment by daspilker** [comment]
:+1: 

Unfortunately the plugin filter does not work perfectly because the `@RequiresPlugin` annotation is missing on several methods, e.g. `ScmContext.github`. That's because `github` calls `git` and having the annotation on both methods will cause duplicate warnings on the console log since the warning will be logged for each annotation. I need to think about a solution. I'm open for ideas.

**Comment by sheehan** [comment]
Can you add a flag to that annotation for whether or not to log the warning?

**Comment by daspilker** [comment]
That would be a solution, but I was looking for something that works automagically. I went with suppressing duplicate warnings, see https://github.com/jenkinsci/job-dsl-plugin/commit/34faf9152844c750c4282ad4440894558a5a037f. I also added all missing annotations, see https://github.com/jenkinsci/job-dsl-plugin/commit/bc1739f8b934506d2dc0ed8832b52a704e2641f7. It's not DRY, but works.

**Comment by sheehan** [comment]
nice!

**Pull request merged**
