### PR TITLE
Adding credentialsId parameter to listTagsParam 

### PR DESCRIPTION
**Pull request by gmatheu**
It adds an additional and optional parameter (credentialsId) to *listTagsParam*

When using **List Tags Param** usually you need to select which credentials should use to retrieve the options.

### CODE REVIEW

**Comment by daspilker** [comment]
The `listTagsParam` is from ancient times and should be replaced by a new variant with a closure parameter instead of adding a 9th parameter. By replacing I mean that the current method should be deprecated and delegate to the new method. Can you do that?

**Comment by gmatheu** [comment]
Sure, I'm gonna create the new method and delegate the call.

**Comment by daspilker** [comment]
OK great, please update the documentation as well.

**Comment by daspilker** [comment]
Oh, and squash your commits to a single one when you are done.

**Comment by jhinrichsen** [comment]
Desperately seeking exactly this feature. Any progress? Need help?

**Comment by daspilker** [comment]
I will take care.

**Comment by daspilker** [comment]
I rebased the changes and merged them manually.

**Pull request closed without merging**
