### PR TITLE
[JENKINS-26636] added publisher for Publish Over SSH plugin

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by jefffiser** [comment]
Will this include the functionality to use a ssh publisher in conditional build steps?

**Comment by daspilker** [comment]
@jefffiser I tested it and it's not working. So it seems to be a different issue. Can you open a new JIRA ticket for the problem?

**Comment by daspilker** [comment]
@jefffiser I started investigating the issue and created [JENKINS-28308](https://issues.jenkins-ci.org/browse/JENKINS-28308)

**Comment by jefffiser** [comment]
@daspilker Thanks for fixing Daniel!

**Pull request merged**
