### PR TITLE
[JENKINS-16356] Show seed job and template job info in the generated job

### PR DESCRIPTION
**Pull request by ceilfors**
Covers JENKINS-16356 and JENKINS-16357.

Sample result:
image

### CODE REVIEW

**Comment by daspilker** [comment]
So, after some intensive yak shaving to upgrade to Jenkins core 1.554, I finally merged your pull request. I rebased and squashed your commits. I also did some heavy refactoring because Jenkins 1.548 introduced a TransientActionFactory which made things simpler. Can you test the current master branch to see if it works for you?

**Comment by ceilfors** [comment]
Thanks.

I have tested it on master branch and it's still working. Though I'm still puzzled of why the updateTransientAction method call is not required anymore (seems like it's called in onLoad but was not triggered last time?!).

I also hit another issue below in the new master branch. Not sure if it's my environment issue or not. I deleted the Service loader file that is causing the issue.

```
Could not instantiate global transform class groovy.grape.GrabAnnotationTransformation specified at jar:file:/Users/ceilfors/github/job-dsl-plugin/work/war/WEB-INF/lib/groovy-all-1.8.9.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception java.lang.ClassNotFoundException: groovy.grape.GrabAnnotationTransformation

1 error

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Could not instantiate global transform class groovy.grape.GrabAnnotationTransformation specified at jar:file:/Users/ceilfors/github/job-dsl-plugin/work/war/WEB-INF/lib/groovy-all-1.8.9.jar!/META-INF/services/org.codehaus.groovy.transform.ASTTransformation  because of exception java.lang.ClassNotFoundException: groovy.grape.GrabAnnotationTransformation

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:302)
	at org.codehaus.groovy.control.ProcessingUnit.completePhase(ProcessingUnit.java:143)
	at org.codehaus.groovy.control.ProcessingUnit.gotoPhase(ProcessingUnit.java:162)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:493)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:258)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:240)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:267)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:214)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:224)
	at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngineForParent(DslScriptLoader.java:58)
	at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngine(DslScriptLoader.java:91)
	at javaposse.jobdsl.plugin.ExecuteDslScripts.perform(ExecuteDslScripts.java:199)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:585)
	at hudson.model.Run.execute(Run.java:1684)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:231)
```

**Comment by daspilker** [comment]
Calling updateTransientAction wasn't a good idea since it's not public. The TransientActionFactory is evaluated everytime when getAction or getAllActions is called. It's different to TransientProjectActionFactory which is evaluated only when updateTransientAction is called.

Matt opened a ticket for the GrabAnnotationTransformation issue: [JENKINS-26377](https://issues.jenkins-ci.org/browse/JENKINS-26377).

**Comment by ceilfors** [comment]
Ah TransientActionFactory is new at 1.548. Thanks, that looks a lot cleaner. :beer:

**Pull request closed without merging**
